# Generated by Django 4.2.7 on 2024-02-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=20, null=True)),
                ('building_name', models.CharField(blank=True, max_length=20, null=True)),
                ('unit_no', models.CharField(default=1, max_length=20)),
                ('tenant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('occupants', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('rent_end_date', models.DateField(blank=True, null=True)),
                ('rent_days', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('month_start_date', models.DateField(blank=True, null=True)),
                ('month_end_date', models.DateField(blank=True, null=True)),
                ('total_bill_days', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('status', models.CharField(choices=[('Fully Stay', 'Fully Stay'), ('Partial Stay', 'Partial Stay'), ('Vacant', 'Vacant')], default='Vacant', max_length=20)),
                ('total_number_of_flats', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_utility_bill_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utility_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family_members', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('utility', models.CharField(max_length=255)),
                ('generation_date', models.DateField()),
                ('vendor', models.CharField(max_length=255)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('flat_no', models.CharField(blank=True, max_length=10, null=True)),
                ('tenant', models.CharField(blank=True, max_length=255, null=True)),
                ('occupants', models.PositiveIntegerField(default=0)),
                ('rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('utility_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.billdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=20, null=True)),
                ('building_name', models.CharField(choices=[], default='', max_length=20)),
                ('unit_no', models.IntegerField(default=1)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bed_rooms', models.IntegerField(default=1)),
                ('bath', models.IntegerField(default=1)),
                ('balcony', models.IntegerField(default=0)),
                ('other', models.CharField(blank=True, max_length=255, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.property')),
            ],
        ),
        migrations.AddField(
            model_name='billdetails',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental_app.building'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.property'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.tenant'),
        ),
        migrations.AddField(
            model_name='billdetails',
            name='utility_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rental_app.utilitybills'),
        ),
    ]
